"""adds Galaxy model

Revision ID: f59bd6e37dde
Revises: 004eca727de3
Create Date: 2023-05-08 15:16:26.731702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59bd6e37dde'
down_revision = '004eca727de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galaxy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('planet', sa.Column('galaxy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planet', 'galaxy', ['galaxy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'galaxy_id')
    op.drop_table('galaxy')
    # ### end Alembic commands ###
